model = "qwen3.8-27b"
model_provider = "llama_cpp"
model_reasoning_effort = "high"

[mcp_servers.duckduckgo-search]
args = ["duckduckgo-mcp-server"]
command = "uvx"

[mcp_servers.reddit]
args = ["simple-reddit-mcp"]
command = "uvx"
