onboarding = false

[terminal]
default_shell = "zsh"

[theme]
name = "kanagawa"
auto_switch = false

[ui]
prompt_new_tab_name = false
pane_outer_borders = false
pane_gaps = false
tab_bar_position = "bottom"

[ui.toast]
delivery = "herdr"

[keys]
detach = "prefix+d"
last_pane = "prefix+l"
focus_agent = "prefix+alt+1..9"

focus_pane_left = "prefix+left"
focus_pane_down = "prefix+down"
focus_pane_up = "prefix+up"
focus_pane_right = "prefix+right"

split_vertical = "prefix+|"
split_horizontal = "prefix+_"

[[keys.command]]
key = "prefix+!"
type = "shell"
command = "herdr pane move \"$HERDR_ACTIVE_PANE_ID\" --new-tab --focus"
description = "Breakout current pane in a new tab."

[[keys.command]]
key = "prefix+j"
type = "popup"
width = "60%"
height = "60%"
command = "bash ~/.config/herdr/scripts/join-pane.sh"
description = "Bring in a pane from another tab"
