[*]
c = 200000
cache-reuse = 256
cache-type-k = f16
cache-type-v = f16
fit = off
flash-attn = on
kv-unified = 1
min-p = 0.0
ngl = 999
no-mmproj = 1
parallel = 2
reasoning-preserve = 1
; TODO: investigate what the ideal value is, based on real usage?
slot-prompt-similarity = 0.5
sm = tensor
spec-draft-n-max = 4
spec-draft-p-min = 0.8
spec-ngram-mod-n-max = 32
spec-ngram-mod-n-min = 16
spec-type = draft-mtp,ngram-mod
threads = 12
threads-batch = 24
top-p = 0.95
ts = 1,1

; TODO: try batch-size/ubatch-size tuning on qwen3.6-26b and gemma4-31b too;
; also worth testing whether gemma4-31b/qwen3.6-26b (currently on automatic
; sm=tensor splitting) would benefit from switching to this manual
; override-tensor + 100,0 tensor-split partitioning scheme instead
[gemma4-31b]
; TODO: apparently quantization really bad for gemma, let's refit for it
fit-target = 2560
hf = unsloth/gemma-4-31b-it-GGUF:UD-Q6_K_XL
temp = 1.0
top-k = 64

[qwen3.6-26b]
chat-template-file = /home/easha/repo/models/templates/qwen-fixed-chat-template.jinja
hf = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q6_K_XL
temp = 0.6
top-k = 20

[qwen3.5-4b]
batch-size = 4096
c = 32768
cache-type-k = q8_0
cache-type-v = q8_0
chat-template-file = /home/easha/repo/models/templates/qwen-fixed-chat-template.jinja
device = CUDA1
hf = unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL
; TODO: given max models set to 1, no reason not to move this to GPU
; that being said, might be worthwhile to preserve (commented) CPU config
ngl = 0
parallel = 1
reasoning = off
sm = none
spec-type = none
temp = 0.7
top-k = 20
top-p = 0.8
ubatch-size = 2048

; [deepseek4-flash]
; ; TODO: experiment with higher batch-size for this and other models
; batch-size = 4096
; cache-type-k = f16
; cache-type-v = f16
; hf = unsloth/DeepSeek-V4-Flash-0731-GGUF:UD-IQ4_NL
; load-mode = none
; ngl = auto
; override-tensor = blk\.[0-2]\.ffn_.*_exps\.weight=CUDA0,blk\.(3[5-9]|4[0-2])\.ffn_.*_exps\.weight=CUDA1,\.ffn_(up|down|gate|gate_up)_(ch|)exps=CPU
; sm = layer
; spec-ngram-mod-n-max = 96
; spec-ngram-mod-n-min = 48
; spec-type = ngram-mod
; temp = 1.0
; tensor-split = 100,0
; ubatch-size = 4096
